---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - oauth2proxy.oauth2proxy-operator.dexter0195.com
  resources:
  - oauth2proxies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - oauth2proxy.oauth2proxy-operator.dexter0195.com
  resources:
  - oauth2proxies/finalizers
  verbs:
  - update
- apiGroups:
  - oauth2proxy.oauth2proxy-operator.dexter0195.com
  resources:
  - oauth2proxies/status
  verbs:
  - get
  - patch
  - update
